config/routes.rb
Rails.application.routes.draw do

  # Static Pages #
  get 'pages/index'

  # Networks #
  resources :networks, only: [:index, :show]

  # Actors #
  resources :actors, only: [:index, :show]

  # Ganres #
  resources :genres, only: [:index, :show]

  # Resources #
  resources :tags, only: [:index, :show]

  # Countries #
  resources :countries, only: [:index, :show]

  # Authentication #
  devise_for :users

  # Admin Control Panel #
  namespace :admin do
    root "application#index"

    resources :actors, only: [:new, :create, :edit, :update, :destroy]
    resources :networks, only: [:new, :create, :edit, :update, :destroy]
    resources :genres, only: [:new, :create, :edit, :update, :destroy]
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
    resources :countries, only: [:new, :create, :edit, :update, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end

  end

  # Root page #
  root "pages#index"

end

app/models/network.rb
class Network < ActiveRecord::Base

  # Validations #
  validates :name, presence: true
  validates :bio, presence: true

  # Uploads #
  has_attached_file :logo, styles: { small: "75x75>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  # Friendly Links #
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end

  # Associations #
  belongs_to :country


end

app/controllers/admin/networks_controller.rb
class Admin::NetworksController < Admin::ApplicationController
  before_action :set_network, only:[:edit, :update, :destroy]

  def new
    @network = Network.new
  end

  def create
    @network = Network.new(network_params)
    if @network.save
      flash[:notice] = "Network has been created."
      redirect_to @network
    else
      flash.now[:alert] = "Network has not been created."
      render 'new'
    end
  end

  def edit
  end

  def update
    if @network.update(network_params)
      flash[:notice] = "Network has been updated."
      redirect_to @network
    else
      flash.now[:alert] = "Network has not been updated."
      render 'edit'
    end
  end

  def destroy
    @network.destroy
    flash[:notice] = "Network has been successfully deleted."
    redirect_to networks_path
  end


  private

    def network_params
      params.require(:network).permit(:name, :bio, :overview, :logo, :country_id)
    end

    def set_network
      @network = Network.friendly.find(params['id'])
    end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_action :set_network, only:[:show]

  def index
    @networks = Network.paginate(:page => params[:page], :per_page => 30).order("name ASC")
  end

  def show

  end
  
  private

    def network_params
      params.require(:network).permit(:name, :bio, :overview, :logo, :country_id)
    end

    def set_network
      @network = Network.friendly.find(params['id'])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The network you were looking for could not be found."
      redirect_to networks_path
    end

end

app/helpers/admin/networks_helper.rb
module Admin::NetworksHelper
end

app/views/networks/_form.html.erb
<%= simple_form_for(network) do |f| %>
  <%= f.input :name %>
  <%= f.input :bio %>
  <%= f.input :overview %>
  <%= f.association :country %>
  <%= f.input :logo, as: :file %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>

<!-- Initialize the editor. -->
<script>
  $(function() {
    $('#network_bio').froalaEditor()
  });
</script>

app/views/networks/index.html.erb
<% title("TV Networks") %>
<div class="row">
  <div class="col-lg-12">
    <section class="networks">
      <header>
        <h1>All TV Networks</h1>
      </header>
      <div class="table-wrapper">
        <table class="table table-bordered">
          <tr>
            <th>
              Logo
            </th>
            <th>
              Name
            </th>
            <th>
              Overview
            </th>
          </tr>
          <% @networks.each do |network| %>
          <tr>
            <td>
              <%= image_tag(network.logo.url(:small), class:"img img-responsive") %>
            </td>
            <td>
              <%= link_to network.name, network %>
            </td>
            <td>
              <%= network.overview %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>
      <div class="pagination-wrapper">
        <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
      </div>
    </section>
  </div>
</div>

app/views/networks/show.html.erb
<% title(@network.name) %>
<section id="tv-network">
  <div class="name-actions">
    <h1><%= @network.name %></h1>
    <ul class="admin-actions">
      <li>
        <%= link_to "Edit Network", edit_admin_network_path(@network), class:"edit" %>
      </li>
      <li>
        <%= link_to "Delete Network", admin_network_path(@network), method: :delete,
                                                                class:"delete",
            data:{confirm:"Are you sure that you want to delete this network?"} %>
      </li>
    </ul>
  </div>

  <div class="row">
    <div class="bio col-xs-12 col-sm-10 col-md-9 col-lg-8">
      <h2>Bio</h2>
      <% unless @network.bio.empty? %>
        <%= @network.bio.html_safe %>
      <% end %>
    </div>
    <div class="sidebar col-xs-12 col-sm-2 col-md-3 col-lg-4">
      <%= image_tag @network.logo, class:"img img-responsive" %>
    </div>
  </div>
</section>