config/routes.rb
Rails.application.routes.draw do

  # Static Pages #
  get 'pages/index'

  # Networks #
  resources :networks, only: [:index, :show]

  # Actors #
  resources :actors, only: [:index, :show]

  # Ganres #
  resources :genres, only: [:index, :show]

  # Resources #
  resources :tags, only: [:index, :show]

  # Countries #
  resources :countries, only: [:index, :show]

  # Authentication #
  devise_for :users

  # Admin Control Panel #
  namespace :admin do
    root "application#index"

    resources :actors, only: [:new, :create, :edit, :update, :destroy]
    resources :networks, only: [:new, :create, :edit, :update, :destroy]
    resources :genres, only: [:new, :create, :edit, :update, :destroy]
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
    resources :countries, only: [:new, :create, :edit, :update, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end

  end

  # Root page #
  root "pages#index"

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  # Validations #
  validates :fullname, presence: true
  validates :bio, presence: true
  validates :overview, presence: true

  # File uploads #
  has_attached_file :image, styles: { preview: "250x320!", medium: "300x350>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  # Friendly Links #
  extend FriendlyId
  friendly_id :fullname, use: :slugged

  def should_generate_new_friendly_id?
    fullname_changed?
  end

  # Associations #
  belongs_to :country

end

app/models/country.rb
class Country < ActiveRecord::Base

  # Validations #
  validates :name, presence: true

  # File uploads #
  has_attached_file :flag, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :flag, content_type: /\Aimage\/.*\Z/

  # Friendly Links #
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end

  # Associations #
  has_many :actors
  has_many :networks

end

app/models/ganre.rb
class Ganre < ActiveRecord::Base

  # Validations #
  validates :name, presence: true
  validates :description, presence: true

  # Friendly Links #
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base

  # Validations #
  validates :name, presence: true
  validates :description, presence: true

  # Friendly Links #
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/models/network.rb
class Network < ActiveRecord::Base

  # Validations #
  validates :name, presence: true
  validates :bio, presence: true

  # Uploads #
  has_attached_file :logo, styles: { small: "75x75>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  # Friendly Links #
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end

  # Associations #
  belongs_to :country


end

app/models/tag.rb
class Tag < ActiveRecord::Base

  # Validations #
  validates :name, presence: true
  validates :description, presence: true

  # Friendly Links #
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  def archive
    self.update(archived_at: Time.now)
 end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
 end

 scope :excluding_archived, lambda { where(archived_at: nil) }
 
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only:[:show]

  def index
    @actors = Actor.all.order("fullname ASC")
  end

  def show
  end

  private

    def actor_params
      params.require(:actor).permit(:fullname, :bio, :image, :date_of_birth, :overview, :country_id, :gender)
    end

    def set_actor
      @actor = Actor.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The actor you were looking for could not be found."
      redirect_to actors_path
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only:[:show]

  def index
    @countries = Country.all
  end

  def show
  end

  private

    def country_params
      params.require(:country).permit(:name, :flag)
    end

    def set_country
      @country = Country.friendly.find(params['id'])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The country you were looking for could not be found."
      redirect_to countries_path
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only:[:show]

  def index
    @genres = Genre.all
  end

  def show
  end

  private

    def genre_params
      params.require(:genre).permit(:name, :description)
    end

    def set_genre
      @genre = Genre.friendly.find(params['id'])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The genre you were looking for could not be found."
      redirect_to genres_path
    end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_action :set_network, only:[:show]

  def index
    @networks = Network.paginate(:page => params[:page], :per_page => 30).order("name ASC")
  end

  def show

  end
  
  private

    def network_params
      params.require(:network).permit(:name, :bio, :overview, :logo, :country_id)
    end

    def set_network
      @network = Network.friendly.find(params['id'])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The network you were looking for could not be found."
      redirect_to networks_path
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only:[:show]

  def index
    @tags = Tag.all
  end

  def show
  end
  
  private

    def tag_params
      params.require(:tag).permit(:name, :description)
    end

    def set_tag
      @tag = Tag.friendly.find(params['id'])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The tag you were looking for could not be found."
      redirect_to tags_path
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Page titles #
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "VoidTV").join(" - ")
      end
    end
  end

  # Check admin status #
  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end

end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/ganres_helper.rb
module GanresHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">VoidTV (0.2)</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to fa_icon('home') + " Home", root_path %>
        </li>
        <li>
          <%= link_to fa_icon("star") + " Actors", actors_path %>
        </li>
        <li>
          <%= link_to fa_icon("building") + " TV Networks", networks_path %>
        </li>
        <li>
          <%= link_to fa_icon("reorder") + " Genres", genres_path %>
        </li>
        <li>
          <%= link_to fa_icon("tags") + " Tags", tags_path %>
        </li>
        <li>
          <%= link_to fa_icon("flag-o") + " Countries", countries_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
        <li>
          <%= link_to fa_icon("user-plus") + " Sign up",
                              new_user_registration_path %>

        </li>
        <li>
          <%= link_to fa_icon("sign-in") + " Sign in", new_user_session_path %>
        </li>
        <% end %>

        <% if user_signed_in? %>
          <% admins_only do %>
            <li>
              <%= link_to fa_icon("dashboard") + " Admin", admin_root_path %>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to fa_icon("sign-out") + " Sign out", destroy_user_session_path,
                                          method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>