config/routes.rb
Rails.application.routes.draw do

  # Static Pages #
  get 'pages/index'

  # Networks #
  resources :networks, only: [:index, :show]

  # Actors #
  resources :actors, only: [:index, :show]

  # Ganres #
  resources :genres, only: [:index, :show]

  # Resources #
  resources :tags, only: [:index, :show]

  # Countries #
  resources :countries, only: [:index, :show]

  # Authentication #
  devise_for :users

  # Admin Control Panel #
  namespace :admin do
    root "application#index"

    resources :actors, only: [:new, :create, :edit, :update, :destroy]
    resources :networks, only: [:new, :create, :edit, :update, :destroy]
    resources :genres, only: [:new, :create, :edit, :update, :destroy]
    resources :tags, only: [:new, :create, :edit, :update, :destroy]
    resources :countries, only: [:new, :create, :edit, :update, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end

  end

  # Root page #
  root "pages#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  def archive
    self.update(archived_at: Time.now)
 end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
 end

 scope :excluding_archived, lambda { where(archived_at: nil) }
 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :archive]

  def index
    @users = User.excluding_archived.order(:email)
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end
    if @user.update(user_params)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been updated."
      render "edit"
    end
  end

  def archive
    if @user == current_user
      flash[:alert] = "You cannot archive yourself!"
    else
      @user.archive
      flash[:notice] = "User has been archived."
    end
    redirect_to admin_users_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :admin)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :admin, label: "Is an admin?" %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/users/edit.html.erb
<header>
  <h1>Edit User</h1>
</header>
<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<header>
  <h1>Users</h1>
  <ul class="actions">
    <li>
      <%= link_to "New User", new_admin_user_path, class: "new" %>
    </li>
  </ul>
</header>


<table class="table table-responsive">
  <tr>
    <th>Id</th>
    <th>Email</th>
    <th>Role</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= link_to user.email, [:admin, user] %></td>
      <td>
        <% if user.admin? %>
          <span class="admin-label">Admin</span>
        <% else %>
          Member
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<header>
  <h1>New User</h1>
</header>
<%= render "form", user: @user %>

app/views/admin/users/show.html.erb
<header>
  <h1><%= @user %></h1>
  <ul class="actions">
    <li>
    <%= link_to "Edit User", [:edit, :admin, @user], class: "edit" %>
    </li>
    <li>
      <%= link_to "Archive User", [:archive, :admin, @user], method: :patch,
      data: { confirm: "Are you sure you want to archive this user?"},
      class: "delete" %>
    </li>
  </ul>
</header>